version: 2
jobs:
   build:
     docker:
       - image: circleci/node:6.10
         environment:
           - PGHOST=localhost
           - PGUSER=postgres
       - image: mdillon/postgis
     
     steps:
       - checkout
       - run: sudo apt-get update
       - run: sudo apt install postgresql-client
       - run: POSTGRES_USER=postgres npm run setup_test_db
       - run: npm install
       - run: npm test
       
       